version: 1
root:
    level: INFO
    handlers:
        - console
        - logtail
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        stream: ext://sys.stdout
        formatter: default
    logtail:
        class: logtail.LogtailHandler
        source_token: REDACTED
        level: INFO
formatters:
    default:
        format: '%(asctime)s %(levelname)-8s %(name)-15s %(filename)-15s %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'